version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./chat-backend
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chat_db
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres

  frontend:
    build: ./chat-frontend
    ports:
      - '3000:80'
    environment:
      - REACT_APP_WS_URL=ws://localhost:8080/ws
    depends_on:
      - backend

volumes:
  postgres_data: 