version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chat_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - RUST_LOG=info
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./chat-frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_WS_URL=ws://localhost:8080/ws
    depends_on:
      - backend

volumes:
  postgres_data: 