app = "mismatch-backend"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["rustlang/cargo"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
  RUST_LOG = "info"

[deploy]
  strategy = "immediate"

[processes]
  app = "./target/release/chat-backend" 