services:
  - type: web
    name: mismatch-backend
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/chat-backend
    repo: https://github.com/YOUR_USERNAME/MisMatch
    branch: main
    rootDir: chat-backend
    envVars:
      - key: PORT
        value: 10000
      - key: RUST_LOG
        value: info
      - key: DB_HOST
        fromDatabase:
          name: mismatch-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mismatch-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: mismatch-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: mismatch-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mismatch-db
          property: password

databases:
  - name: mismatch-db
    databaseName: mismatch
    user: mismatch 